export interface GameEditionMeta {
  title: string;
  shortTitle: string;
  generation: number;
  genLabel: string;
  console: string;
  region: string;
  color: string;
  borderColor: string;
  gradient: string;
  badgeBg: string;
  group: 'gen1-3' | 'gen4-5' | 'gen6-7' | 'gen8-9';
}

export const GAME_EDITIONS_META: Record<string, GameEditionMeta> = {
  // Gen 1 (GB)
  red: {
    title: 'Pokémon Red',
    shortTitle: 'Red',
    generation: 1,
    genLabel: 'GEN I',
    console: 'Game Boy',
    region: 'Kanto',
    color: '#ef4444',
    borderColor: '#dc2626',
    gradient: 'linear-gradient(135deg, rgba(220, 38, 38, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(239, 68, 68, 0.2)',
    group: 'gen1-3',
  },
  blue: {
    title: 'Pokémon Blue',
    shortTitle: 'Blue',
    generation: 1,
    genLabel: 'GEN I',
    console: 'Game Boy',
    region: 'Kanto',
    color: '#3b82f6',
    borderColor: '#2563eb',
    gradient: 'linear-gradient(135deg, rgba(37, 99, 235, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(59, 130, 246, 0.2)',
    group: 'gen1-3',
  },
  yellow: {
    title: 'Pokémon Yellow (Special Pikachu Edition)',
    shortTitle: 'Yellow',
    generation: 1,
    genLabel: 'GEN I',
    console: 'Game Boy',
    region: 'Kanto',
    color: '#eab308',
    borderColor: '#ca8a04',
    gradient: 'linear-gradient(135deg, rgba(202, 138, 4, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(234, 179, 8, 0.2)',
    group: 'gen1-3',
  },
  'red-japan': {
    title: 'Pocket Monsters Red (JP)',
    shortTitle: 'Red JP',
    generation: 1,
    genLabel: 'GEN I',
    console: 'Game Boy',
    region: 'Kanto',
    color: '#ef4444',
    borderColor: '#dc2626',
    gradient: 'linear-gradient(135deg, rgba(220, 38, 38, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(239, 68, 68, 0.2)',
    group: 'gen1-3',
  },
  'green-japan': {
    title: 'Pocket Monsters Green (JP)',
    shortTitle: 'Green JP',
    generation: 1,
    genLabel: 'GEN I',
    console: 'Game Boy',
    region: 'Kanto',
    color: '#22c55e',
    borderColor: '#16a34a',
    gradient: 'linear-gradient(135deg, rgba(22, 163, 74, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(34, 197, 94, 0.2)',
    group: 'gen1-3',
  },
  'blue-japan': {
    title: 'Pocket Monsters Blue (JP)',
    shortTitle: 'Blue JP',
    generation: 1,
    genLabel: 'GEN I',
    console: 'Game Boy',
    region: 'Kanto',
    color: '#3b82f6',
    borderColor: '#2563eb',
    gradient: 'linear-gradient(135deg, rgba(37, 99, 235, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(59, 130, 246, 0.2)',
    group: 'gen1-3',
  },

  // Gen 2 (GBC)
  gold: {
    title: 'Pokémon Gold',
    shortTitle: 'Gold',
    generation: 2,
    genLabel: 'GEN II',
    console: 'Game Boy Color',
    region: 'Johto / Kanto',
    color: '#f59e0b',
    borderColor: '#d97706',
    gradient: 'linear-gradient(135deg, rgba(217, 119, 6, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(245, 158, 11, 0.2)',
    group: 'gen1-3',
  },
  silver: {
    title: 'Pokémon Silver',
    shortTitle: 'Silver',
    generation: 2,
    genLabel: 'GEN II',
    console: 'Game Boy Color',
    region: 'Johto / Kanto',
    color: '#94a3b8',
    borderColor: '#64748b',
    gradient: 'linear-gradient(135deg, rgba(100, 116, 139, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(148, 163, 184, 0.2)',
    group: 'gen1-3',
  },
  crystal: {
    title: 'Pokémon Crystal',
    shortTitle: 'Crystal',
    generation: 2,
    genLabel: 'GEN II',
    console: 'Game Boy Color',
    region: 'Johto / Kanto',
    color: '#06b6d4',
    borderColor: '#0891b2',
    gradient: 'linear-gradient(135deg, rgba(8, 145, 178, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(6, 182, 212, 0.2)',
    group: 'gen1-3',
  },

  // Gen 3 (GBA)
  ruby: {
    title: 'Pokémon Ruby',
    shortTitle: 'Ruby',
    generation: 3,
    genLabel: 'GEN III',
    console: 'Game Boy Advance',
    region: 'Hoenn',
    color: '#e11d48',
    borderColor: '#be123c',
    gradient: 'linear-gradient(135deg, rgba(190, 18, 60, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(225, 29, 72, 0.2)',
    group: 'gen1-3',
  },
  sapphire: {
    title: 'Pokémon Sapphire',
    shortTitle: 'Sapphire',
    generation: 3,
    genLabel: 'GEN III',
    console: 'Game Boy Advance',
    region: 'Hoenn',
    color: '#2563eb',
    borderColor: '#1d4ed8',
    gradient: 'linear-gradient(135deg, rgba(29, 78, 216, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(37, 99, 235, 0.2)',
    group: 'gen1-3',
  },
  emerald: {
    title: 'Pokémon Emerald',
    shortTitle: 'Emerald',
    generation: 3,
    genLabel: 'GEN III',
    console: 'Game Boy Advance',
    region: 'Hoenn',
    color: '#10b981',
    borderColor: '#059669',
    gradient: 'linear-gradient(135deg, rgba(5, 150, 105, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(16, 185, 129, 0.2)',
    group: 'gen1-3',
  },
  firered: {
    title: 'Pokémon FireRed',
    shortTitle: 'FireRed',
    generation: 3,
    genLabel: 'GEN III',
    console: 'Game Boy Advance',
    region: 'Kanto / Sevii',
    color: '#f97316',
    borderColor: '#ea580c',
    gradient: 'linear-gradient(135deg, rgba(234, 88, 12, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(249, 115, 22, 0.2)',
    group: 'gen1-3',
  },
  leafgreen: {
    title: 'Pokémon LeafGreen',
    shortTitle: 'LeafGreen',
    generation: 3,
    genLabel: 'GEN III',
    console: 'Game Boy Advance',
    region: 'Kanto / Sevii',
    color: '#84cc16',
    borderColor: '#65a30d',
    gradient: 'linear-gradient(135deg, rgba(101, 163, 13, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(132, 204, 22, 0.2)',
    group: 'gen1-3',
  },
  colosseum: {
    title: 'Pokémon Colosseum',
    shortTitle: 'Colosseum',
    generation: 3,
    genLabel: 'GEN III',
    console: 'GameCube',
    region: 'Orre',
    color: '#a855f7',
    borderColor: '#9333ea',
    gradient: 'linear-gradient(135deg, rgba(147, 51, 234, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(168, 85, 247, 0.2)',
    group: 'gen1-3',
  },
  xd: {
    title: 'Pokémon XD: Gale of Darkness',
    shortTitle: 'XD',
    generation: 3,
    genLabel: 'GEN III',
    console: 'GameCube',
    region: 'Orre',
    color: '#6366f1',
    borderColor: '#4f46e5',
    gradient: 'linear-gradient(135deg, rgba(79, 70, 229, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(99, 102, 241, 0.2)',
    group: 'gen1-3',
  },

  // Gen 4 (NDS)
  diamond: {
    title: 'Pokémon Diamond',
    shortTitle: 'Diamond',
    generation: 4,
    genLabel: 'GEN IV',
    console: 'Nintendo DS',
    region: 'Sinnoh',
    color: '#38bdf8',
    borderColor: '#0284c7',
    gradient: 'linear-gradient(135deg, rgba(2, 132, 199, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(56, 189, 248, 0.2)',
    group: 'gen4-5',
  },
  pearl: {
    title: 'Pokémon Pearl',
    shortTitle: 'Pearl',
    generation: 4,
    genLabel: 'GEN IV',
    console: 'Nintendo DS',
    region: 'Sinnoh',
    color: '#f472b6',
    borderColor: '#db2777',
    gradient: 'linear-gradient(135deg, rgba(219, 39, 119, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(244, 114, 182, 0.2)',
    group: 'gen4-5',
  },
  platinum: {
    title: 'Pokémon Platinum',
    shortTitle: 'Platinum',
    generation: 4,
    genLabel: 'GEN IV',
    console: 'Nintendo DS',
    region: 'Sinnoh / Distortion',
    color: '#94a3b8',
    borderColor: '#475569',
    gradient: 'linear-gradient(135deg, rgba(71, 85, 105, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(148, 163, 184, 0.2)',
    group: 'gen4-5',
  },
  heartgold: {
    title: 'Pokémon HeartGold',
    shortTitle: 'HeartGold',
    generation: 4,
    genLabel: 'GEN IV',
    console: 'Nintendo DS',
    region: 'Johto / Kanto',
    color: '#fbbf24',
    borderColor: '#d97706',
    gradient: 'linear-gradient(135deg, rgba(217, 119, 6, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(251, 191, 36, 0.2)',
    group: 'gen4-5',
  },
  soulsilver: {
    title: 'Pokémon SoulSilver',
    shortTitle: 'SoulSilver',
    generation: 4,
    genLabel: 'GEN IV',
    console: 'Nintendo DS',
    region: 'Johto / Kanto',
    color: '#cbd5e1',
    borderColor: '#64748b',
    gradient: 'linear-gradient(135deg, rgba(100, 116, 139, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(203, 213, 225, 0.2)',
    group: 'gen4-5',
  },

  // Gen 5 (NDS)
  black: {
    title: 'Pokémon Black',
    shortTitle: 'Black',
    generation: 5,
    genLabel: 'GEN V',
    console: 'Nintendo DS',
    region: 'Unova',
    color: '#e2e8f0',
    borderColor: '#334155',
    gradient: 'linear-gradient(135deg, rgba(30, 41, 59, 0.5) 0%, rgba(15, 23, 42, 0.95) 100%)',
    badgeBg: 'rgba(226, 232, 240, 0.15)',
    group: 'gen4-5',
  },
  white: {
    title: 'Pokémon White',
    shortTitle: 'White',
    generation: 5,
    genLabel: 'GEN V',
    console: 'Nintendo DS',
    region: 'Unova',
    color: '#f8fafc',
    borderColor: '#94a3b8',
    gradient: 'linear-gradient(135deg, rgba(148, 163, 184, 0.2) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(248, 250, 252, 0.2)',
    group: 'gen4-5',
  },
  'black-2': {
    title: 'Pokémon Black 2',
    shortTitle: 'Black 2',
    generation: 5,
    genLabel: 'GEN V',
    console: 'Nintendo DS',
    region: 'Unova',
    color: '#38bdf8',
    borderColor: '#0284c7',
    gradient: 'linear-gradient(135deg, rgba(2, 132, 199, 0.25) 0%, rgba(15, 23, 42, 0.95) 100%)',
    badgeBg: 'rgba(56, 189, 248, 0.2)',
    group: 'gen4-5',
  },
  'white-2': {
    title: 'Pokémon White 2',
    shortTitle: 'White 2',
    generation: 5,
    genLabel: 'GEN V',
    console: 'Nintendo DS',
    region: 'Unova',
    color: '#fb7185',
    borderColor: '#e11d48',
    gradient: 'linear-gradient(135deg, rgba(225, 29, 72, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(251, 113, 133, 0.2)',
    group: 'gen4-5',
  },

  // Gen 6 (3DS)
  x: {
    title: 'Pokémon X',
    shortTitle: 'X',
    generation: 6,
    genLabel: 'GEN VI',
    console: 'Nintendo 3DS',
    region: 'Kalos',
    color: '#0284c7',
    borderColor: '#0369a1',
    gradient: 'linear-gradient(135deg, rgba(3, 105, 161, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(2, 132, 199, 0.2)',
    group: 'gen6-7',
  },
  y: {
    title: 'Pokémon Y',
    shortTitle: 'Y',
    generation: 6,
    genLabel: 'GEN VI',
    console: 'Nintendo 3DS',
    region: 'Kalos',
    color: '#e11d48',
    borderColor: '#be123c',
    gradient: 'linear-gradient(135deg, rgba(190, 18, 60, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(225, 29, 72, 0.2)',
    group: 'gen6-7',
  },
  'omega-ruby': {
    title: 'Pokémon Omega Ruby',
    shortTitle: 'Omega Ruby',
    generation: 6,
    genLabel: 'GEN VI',
    console: 'Nintendo 3DS',
    region: 'Hoenn',
    color: '#ef4444',
    borderColor: '#b91c1c',
    gradient: 'linear-gradient(135deg, rgba(185, 28, 28, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(239, 68, 68, 0.2)',
    group: 'gen6-7',
  },
  'alpha-sapphire': {
    title: 'Pokémon Alpha Sapphire',
    shortTitle: 'Alpha Sapphire',
    generation: 6,
    genLabel: 'GEN VI',
    console: 'Nintendo 3DS',
    region: 'Hoenn',
    color: '#2563eb',
    borderColor: '#1d4ed8',
    gradient: 'linear-gradient(135deg, rgba(29, 78, 216, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(37, 99, 235, 0.2)',
    group: 'gen6-7',
  },

  // Gen 7 (3DS / Switch)
  sun: {
    title: 'Pokémon Sun',
    shortTitle: 'Sun',
    generation: 7,
    genLabel: 'GEN VII',
    console: 'Nintendo 3DS',
    region: 'Alola',
    color: '#f59e0b',
    borderColor: '#d97706',
    gradient: 'linear-gradient(135deg, rgba(217, 119, 6, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(245, 158, 11, 0.2)',
    group: 'gen6-7',
  },
  moon: {
    title: 'Pokémon Moon',
    shortTitle: 'Moon',
    generation: 7,
    genLabel: 'GEN VII',
    console: 'Nintendo 3DS',
    region: 'Alola',
    color: '#a855f7',
    borderColor: '#7e22ce',
    gradient: 'linear-gradient(135deg, rgba(126, 34, 206, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(168, 85, 247, 0.2)',
    group: 'gen6-7',
  },
  'ultra-sun': {
    title: 'Pokémon Ultra Sun',
    shortTitle: 'Ultra Sun',
    generation: 7,
    genLabel: 'GEN VII',
    console: 'Nintendo 3DS',
    region: 'Alola / Ultra Space',
    color: '#ea580c',
    borderColor: '#c2410c',
    gradient: 'linear-gradient(135deg, rgba(194, 65, 12, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(234, 88, 12, 0.2)',
    group: 'gen6-7',
  },
  'ultra-moon': {
    title: 'Pokémon Ultra Moon',
    shortTitle: 'Ultra Moon',
    generation: 7,
    genLabel: 'GEN VII',
    console: 'Nintendo 3DS',
    region: 'Alola / Ultra Space',
    color: '#9333ea',
    borderColor: '#6b21a8',
    gradient: 'linear-gradient(135deg, rgba(107, 33, 168, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(147, 51, 234, 0.2)',
    group: 'gen6-7',
  },
  'lets-go-pikachu': {
    title: "Pokémon: Let's Go, Pikachu!",
    shortTitle: "Let's Go Pikachu",
    generation: 7,
    genLabel: 'GEN VII',
    console: 'Nintendo Switch',
    region: 'Kanto',
    color: '#eab308',
    borderColor: '#ca8a04',
    gradient: 'linear-gradient(135deg, rgba(202, 138, 4, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(234, 179, 8, 0.2)',
    group: 'gen6-7',
  },
  'lets-go-eevee': {
    title: "Pokémon: Let's Go, Eevee!",
    shortTitle: "Let's Go Eevee",
    generation: 7,
    genLabel: 'GEN VII',
    console: 'Nintendo Switch',
    region: 'Kanto',
    color: '#b45309',
    borderColor: '#78350f',
    gradient: 'linear-gradient(135deg, rgba(120, 53, 15, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(180, 83, 9, 0.2)',
    group: 'gen6-7',
  },

  // Gen 8 (Switch)
  sword: {
    title: 'Pokémon Sword',
    shortTitle: 'Sword',
    generation: 8,
    genLabel: 'GEN VIII',
    console: 'Nintendo Switch',
    region: 'Galar',
    color: '#0284c7',
    borderColor: '#0369a1',
    gradient: 'linear-gradient(135deg, rgba(3, 105, 161, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(2, 132, 199, 0.2)',
    group: 'gen8-9',
  },
  shield: {
    title: 'Pokémon Shield',
    shortTitle: 'Shield',
    generation: 8,
    genLabel: 'GEN VIII',
    console: 'Nintendo Switch',
    region: 'Galar',
    color: '#e11d48',
    borderColor: '#be123c',
    gradient: 'linear-gradient(135deg, rgba(190, 18, 60, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(225, 29, 72, 0.2)',
    group: 'gen8-9',
  },
  'the-isle-of-armor-sword': {
    title: 'Pokémon Sword: The Isle of Armor',
    shortTitle: 'Isle of Armor (Sword)',
    generation: 8,
    genLabel: 'GEN VIII DLC',
    console: 'Nintendo Switch',
    region: 'Isle of Armor (Galar)',
    color: '#eab308',
    borderColor: '#ca8a04',
    gradient: 'linear-gradient(135deg, rgba(202, 138, 4, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(234, 179, 8, 0.2)',
    group: 'gen8-9',
  },
  'the-isle-of-armor-shield': {
    title: 'Pokémon Shield: The Isle of Armor',
    shortTitle: 'Isle of Armor (Shield)',
    generation: 8,
    genLabel: 'GEN VIII DLC',
    console: 'Nintendo Switch',
    region: 'Isle of Armor (Galar)',
    color: '#eab308',
    borderColor: '#ca8a04',
    gradient: 'linear-gradient(135deg, rgba(202, 138, 4, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(234, 179, 8, 0.2)',
    group: 'gen8-9',
  },
  'the-crown-tundra-sword': {
    title: 'Pokémon Sword: The Crown Tundra',
    shortTitle: 'Crown Tundra (Sword)',
    generation: 8,
    genLabel: 'GEN VIII DLC',
    console: 'Nintendo Switch',
    region: 'Crown Tundra (Galar)',
    color: '#06b6d4',
    borderColor: '#0891b2',
    gradient: 'linear-gradient(135deg, rgba(8, 145, 178, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(6, 182, 212, 0.2)',
    group: 'gen8-9',
  },
  'the-crown-tundra-shield': {
    title: 'Pokémon Shield: The Crown Tundra',
    shortTitle: 'Crown Tundra (Shield)',
    generation: 8,
    genLabel: 'GEN VIII DLC',
    console: 'Nintendo Switch',
    region: 'Crown Tundra (Galar)',
    color: '#06b6d4',
    borderColor: '#0891b2',
    gradient: 'linear-gradient(135deg, rgba(8, 145, 178, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(6, 182, 212, 0.2)',
    group: 'gen8-9',
  },
  'brilliant-diamond': {
    title: 'Pokémon Brilliant Diamond',
    shortTitle: 'Brilliant Diamond',
    generation: 8,
    genLabel: 'GEN VIII',
    console: 'Nintendo Switch',
    region: 'Sinnoh',
    color: '#38bdf8',
    borderColor: '#0284c7',
    gradient: 'linear-gradient(135deg, rgba(2, 132, 199, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(56, 189, 248, 0.2)',
    group: 'gen8-9',
  },
  'shining-pearl': {
    title: 'Pokémon Shining Pearl',
    shortTitle: 'Shining Pearl',
    generation: 8,
    genLabel: 'GEN VIII',
    console: 'Nintendo Switch',
    region: 'Sinnoh',
    color: '#f472b6',
    borderColor: '#db2777',
    gradient: 'linear-gradient(135deg, rgba(219, 39, 119, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(244, 114, 182, 0.2)',
    group: 'gen8-9',
  },
  'legends-arceus': {
    title: 'Pokémon Legends: Arceus',
    shortTitle: 'Legends Arceus',
    generation: 8,
    genLabel: 'GEN VIII',
    console: 'Nintendo Switch',
    region: 'Hisui',
    color: '#10b981',
    borderColor: '#059669',
    gradient: 'linear-gradient(135deg, rgba(5, 150, 105, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(16, 185, 129, 0.2)',
    group: 'gen8-9',
  },

  // Gen 9 (Switch)
  scarlet: {
    title: 'Pokémon Scarlet',
    shortTitle: 'Scarlet',
    generation: 9,
    genLabel: 'GEN IX',
    console: 'Nintendo Switch',
    region: 'Paldea',
    color: '#ef4444',
    borderColor: '#dc2626',
    gradient: 'linear-gradient(135deg, rgba(220, 38, 38, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(239, 68, 68, 0.2)',
    group: 'gen8-9',
  },
  violet: {
    title: 'Pokémon Violet',
    shortTitle: 'Violet',
    generation: 9,
    genLabel: 'GEN IX',
    console: 'Nintendo Switch',
    region: 'Paldea',
    color: '#8b5cf6',
    borderColor: '#7c3aed',
    gradient: 'linear-gradient(135deg, rgba(124, 58, 237, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(139, 92, 246, 0.2)',
    group: 'gen8-9',
  },
  'the-teal-mask': {
    title: 'Pokémon Scarlet/Violet: The Teal Mask',
    shortTitle: 'Teal Mask',
    generation: 9,
    genLabel: 'GEN IX DLC',
    console: 'Nintendo Switch',
    region: 'Kitakami',
    color: '#14b8a6',
    borderColor: '#0d9488',
    gradient: 'linear-gradient(135deg, rgba(13, 148, 136, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(20, 184, 166, 0.2)',
    group: 'gen8-9',
  },
  'the-indigo-disk': {
    title: 'Pokémon Scarlet/Violet: The Indigo Disk',
    shortTitle: 'Indigo Disk',
    generation: 9,
    genLabel: 'GEN IX DLC',
    console: 'Nintendo Switch',
    region: 'Terarium (Unova Sea)',
    color: '#3b82f6',
    borderColor: '#2563eb',
    gradient: 'linear-gradient(135deg, rgba(37, 99, 235, 0.25) 0%, rgba(15, 23, 42, 0.9) 100%)',
    badgeBg: 'rgba(59, 130, 246, 0.2)',
    group: 'gen8-9',
  },
};

export interface EncounterMethodMeta {
  label: string;
  category: 'walk' | 'water' | 'rod' | 'rock' | 'tree' | 'cave' | 'special';
  color: string;
}

export const ENCOUNTER_METHODS_META: Record<string, EncounterMethodMeta> = {
  walk: { label: 'Andando na Grama', category: 'walk', color: '#4ade80' },
  'dark-grass': { label: 'Grama Escura (Dupla)', category: 'walk', color: '#16a34a' },
  'rustling-grass': { label: 'Grama Farfalhante', category: 'walk', color: '#84cc16' },
  surf: { label: 'Surfando na Água', category: 'water', color: '#38bdf8' },
  'bridge-spots': { label: 'Sombras em Pontes', category: 'water', color: '#0ea5e9' },
  'seaweed': { label: 'Algas Marinhas', category: 'water', color: '#2dd4bf' },
  'old-rod': { label: 'Vara Velha (Pesca)', category: 'rod', color: '#60a5fa' },
  'good-rod': { label: 'Vara Boa (Pesca)', category: 'rod', color: '#818cf8' },
  'super-rod': { label: 'Super Vara (Pesca)', category: 'rod', color: '#a78bfa' },
  'fish': { label: 'Pescaria', category: 'rod', color: '#38bdf8' },
  'rock-smash': { label: 'Quebrando Rochas', category: 'rock', color: '#fb923c' },
  'headbutt': { label: 'Cabeçada em Árvore', category: 'tree', color: '#a3e635' },
  'cave': { label: 'Interior de Caverna', category: 'cave', color: '#c084fc' },
  'gift': { label: 'Presente / Inicial', category: 'special', color: '#f472b6' },
  'gift-egg': { label: 'Ovo de Presente', category: 'special', color: '#fb7185' },
  'only-one': { label: 'Encontro Estático / Lendário', category: 'special', color: '#facc15' },
  'static': { label: 'Encontro Estático', category: 'special', color: '#facc15' },
  'poke-radar': { label: 'Poké Radar', category: 'special', color: '#06b6d4' },
  'island-scan': { label: 'Scanner Insular', category: 'special', color: '#2dd4bf' },
  'curse-grass': { label: 'Grama Sombria', category: 'walk', color: '#94a3b8' },
  'squirtbottle': { label: 'Regador (Sudowoodo)', category: 'special', color: '#38bdf8' },
  'wailmer-pail': { label: 'Regador Wailmer', category: 'special', color: '#38bdf8' },
};

/**
 * Format messy API location area names into pleasant, human-readable Brazilian Portuguese titles
 */
export function formatLocationAreaName(rawName: string): string {
  if (!rawName) return 'Área Desconhecida';

  let clean = rawName.toLowerCase();

  // Remove common trailing area suffixes
  clean = clean.replace(/-area$/i, '').replace(/-unknown$/i, '');

  // Common replacements for regions & landmarks
  const replacements: [RegExp, string][] = [
    [/^kanto-route-(\d+)/i, 'Rota $1 (Kanto)'],
    [/^johto-route-(\d+)/i, 'Rota $1 (Johto)'],
    [/^hoenn-route-(\d+)/i, 'Rota $1 (Hoenn)'],
    [/^sinnoh-route-(\d+)/i, 'Rota $1 (Sinnoh)'],
    [/^unova-route-(\d+)/i, 'Rota $1 (Unova)'],
    [/^kalos-route-(\d+)/i, 'Rota $1 (Kalos)'],
    [/^alola-route-(\d+)/i, 'Rota $1 (Alola)'],
    [/^galar-route-(\d+)/i, 'Rota $1 (Galar)'],
    [/^route-(\d+)/i, 'Rota $1'],
    [/^sea-route-(\d+)/i, 'Rota Marítima $1'],
    [/^underwater-route-(\d+)/i, 'Submarino: Rota $1'],
    [/viridian-forest/i, 'Floresta de Viridian'],
    [/cerulean-cave/i, 'Caverna de Cerulean'],
    [/mt-moon/i, 'Monte Moon'],
    [/rock-tunnel/i, 'Túnel de Rocha'],
    [/digletts-cave/i, 'Caverna dos Diglett'],
    [/pokemon-tower/i, 'Torre Pokémon (Lavender)'],
    [/safari-zone/i, 'Zona Safari'],
    [/seafoam-islands/i, 'Ilhas Seafoam'],
    [/power-plant/i, 'Usina Elétrica'],
    [/victory-road/i, 'Estrada da Vitória (Victory Road)'],
    [/trophy-garden/i, 'Jardim dos Troféus (Trophy Garden)'],
    [/great-marsh/i, 'Grande Pântano (Great Marsh)'],
    [/solaceon-ruins/i, 'Ruínas de Solaceon'],
    [/mt-coronet/i, 'Monte Coronet'],
    [/sendoff-spring/i, 'Nascente da Despedida (Sendoff Spring)'],
    [/turnback-cave/i, 'Caverna do Retorno (Turnback Cave)'],
    [/lake-verity/i, 'Lago da Veracidade (Verity)'],
    [/lake-valor/i, 'Lago do Valor'],
    [/lake-acuity/i, 'Lago da Agudeza (Acuity)'],
    [/illex-forest/i, 'Floresta de Ilex'],
    [/national-park/i, 'Parque Nacional'],
    [/burned-tower/i, 'Torre Queimada'],
    [/bell-tower|tin-tower/i, 'Torre do Sino (Bell Tower)'],
    [/whirl-islands/i, 'Ilhas dos Redemoinhos (Whirl Islands)'],
    [/mt-silver/i, 'Monte Silver'],
    [/petalburg-woods/i, 'Bosque de Petalburg'],
    [/granite-cave/i, 'Caverna de Granito'],
    [/meteor-falls/i, 'Quedas Meteoro (Meteor Falls)'],
    [/fiery-path/i, 'Caminho Flamejante (Fiery Path)'],
    [/jagged-pass/i, 'Passo Escarpado (Jagged Pass)'],
    [/mt-pyre/i, 'Monte Pyre'],
    [/shoal-cave/i, 'Caverna Shoal'],
    [/cave-of-origin/i, 'Caverna da Origem'],
    [/sky-pillar/i, 'Pilar Celeste (Sky Pillar)'],
    [/wild-area/i, 'Área Selvagem (Wild Area)'],
    [/slumbering-weald/i, 'Bosque Adormecido (Slumbering Weald)'],
    [/glimwood-tangle/i, 'Bosque de Glimwood'],
    [/crown-tundra/i, 'Tundra da Coroa (Crown Tundra)'],
    [/isle-of-armor/i, 'Ilha da Armadura (Isle of Armor)'],
    [/max-lair/i, 'Covil Max (Max Lair / Dynamax Adventures)'],
    [/casseroya-lake/i, 'Lago Casseroya (Paldea)'],
    [/area-zero/i, 'Área Zero (Grande Cratera de Paldea)'],
    [/tagtree-thicket/i, 'Bosque de Tagtree'],
    [/asado-desert/i, 'Deserto de Asado'],
    [/dalizapa-passage/i, 'Passagem Dalizapa'],
    [/glaseado-mountain/i, 'Montanha Glaseado'],
    [/socarrat-trail/i, 'Trilha Socarrat'],
    [/kitakami-wilds/i, 'Selvas de Kitakami'],
    [/oni-mountain/i, 'Monte Oni'],
    [/terarium/i, 'Terário da Academia Blueberry'],
  ];

  for (const [pattern, replacement] of replacements) {
    if (pattern.test(clean)) {
      clean = clean.replace(pattern, replacement);
      break;
    }
  }

  // Generic formatting for anything unmapped
  return clean
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
